<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="PI" value="3.14159265359" />
    <xacro:property name="CAM_R" value="0.00425" />
    <xacro:property name="CAM_L" value="0.001" />
    <xacro:property name="CAM_OFF_X" value="0.1" />
    <xacro:property name="CAM_OFF_Z" value="0.05" />
    <xacro:property name="CAM_M" value="0.17" />

    <joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${CAM_OFF_X} 0 ${BASE_Z/2+CAM_R+CAM_OFF_Z}" rpy="0 ${-PI/2} 0"/>
    </joint>

    <link name="camera">
        <visual>
            <geometry>
                <cylinder radius="${CAM_R}" length="${CAM_L}" />
            </geometry>
            <material name="green" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${CAM_R}" length="${CAM_L}" />
            </geometry>
        </collision>

        <xacro:CylinderInertial m="${CAM_M}" r="${CAM_R}" l="${CAM_L}" />

    </link>

    <gazebo reference="camera">
        <material>Gazebo/Green</material>
        <sensor name="rgb_camera" type="camera">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>20.0</update_rate>
            <camera name="rgb_camera">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                  <width>800</width>
                  <height>800</height>
                  <format>R8G8B8</format>
                </image>
                <clip>
                  <near>0.02</near>
                  <far>300</far>
                </clip>
                <noise>
                  <type>gaussian</type>
                  <!-- Noise is sampled independently per pixel on each frame.
                       That pixel's noise value is added to each of its color
                       channels, which at that point lie in the range [0,1]. -->
                  <mean>0.0</mean>
                  <stddev>0.007</stddev>
                </noise>
                <distortion>
                    <k1>0.1</k1>
                    <k2>0.1</k2>
                    <k3>0.1</k3>
                    <p1>0.1</p1>
                    <p2>0.1</p2>
                    <center>0.5 0.5</center>
                </distortion>
            </camera>

            <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
                <!-- Change namespace, camera name and topics so -
                     * Images are published to: /custom_ns/custom_camera/custom_image
                     * Camera info is published to: /custom_ns/custom_camera/custom_info
                -->
                <!-- <ros>
                  <namespace>custom_ns</namespace>
                  <remapping>image_raw:=custom_img</remapping>
                  <remapping>camera_info:=custom_info</remapping>
                </ros> -->
    
                <!-- Set camera name. If empty, defaults to sensor name (i.e. "sensor_name") -->
                <!-- <camera_name>custom_camera</camera_name> -->
    
                <!-- Set TF frame name. If empty, defaults to link name (i.e. "link_name") -->
                <!-- <frame_name>custom_frame</frame_name> -->
    
                <hack_baseline>0.07</hack_baseline>
    
                <!-- No need to repeat distortion parameters or to set autoDistortion -->
              </plugin>   
        </sensor>
    </gazebo>
    
</robot>