<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="IMU_X" value="0.05" />
    <xacro:property name="IMU_Y" value="0.035" />
    <xacro:property name="IMU_Z" value="0.002" />
    <xacro:property name="IMU_OFF_X" value="0.075" />
    <xacro:property name="IMU_OFF_Z" value="0.01" />
    <xacro:property name="IMU_M" value="0.005" />

    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu" />
        <origin xyz="${IMU_OFF_X} 0 ${(BASE_Z+IMU_Z)/2+IMU_OFF_Z}" />
    </joint>

    <link name="imu">
        <visual>
            <geometry>
                <box size="${IMU_X} ${IMU_Y} ${IMU_Z}" />
            </geometry>
            <material name="black" />
        </visual>

        <collision>
            <geometry>
                <box size="${IMU_X} ${IMU_Y} ${IMU_Z}" />
            </geometry>
        </collision>

        <xacro:BoxInertial m="${IMU_M}" x="${IMU_X}" y="${IMU_Y}" z="${IMU_Z}" />
    </link>

</robot>