<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
        <!-- Constants -->
        <xacro:property name="PI" value="3.14159265359" />

        <xacro:property name="BASE_X" value="1.0" />
        <xacro:property name="BASE_Y" value="0.8" />
        <xacro:property name="BASE_Z" value="0.4" />
        <xacro:property name="BASE_M" value="4" />
        
        <xacro:property name="CASTER_OFF_X" value="-0.4" />
        <xacro:property name="CASTER_OFF_Z" value="-0.2" />
        <xacro:property name="CASTER_R" value="0.1" />
        <xacro:property name="CASTER_M" value="1.0" />
    
        <xacro:property name="WHEEL_OFF_X" value="0.2" />
        <xacro:property name="WHEEL_OFF_Y" value="0.5" />
        <xacro:property name="WHEEL_R" value="0.3" />
        <xacro:property name="WHEEL_L" value="0.1" />
        <xacro:property name="WHEEL_M" value="0.5" />
    
        <xacro:property name="LIDAR_OFF_Z" value="0.35" />
        <xacro:property name="LIDAR_R" value="0.035" />
        <xacro:property name="LIDAR_L" value="0.02" />
        <xacro:property name="LIDAR_M" value="0.17" />
        
        <!-- Wheel macro -->
        <xacro:macro name="Wheel" params="prefix y_reflect">
            <joint name="${prefix}_wheel_joint" type="continuous">
                <parent link="base_link" />
                <child link="${prefix}_wheel" />
                <origin xyz="${WHEEL_OFF_X} ${y_reflect*WHEEL_OFF_Y} 0" rpy="${-PI/2} 0 0" />
                <axis xyz="0 0 1" />
            </joint>
    
            <link name="${prefix}_wheel">
                <visual>
                    <geometry>
                        <cylinder radius="${WHEEL_R}" length="${WHEEL_L}" />
                    </geometry>
                    <material name="black" />
                </visual>
    
                <collision>
                    <geometry>
                        <cylinder radius="${WHEEL_R}" length="${WHEEL_L}" />
                    </geometry>
                </collision>
    
                <xacro:CylinderInertial m="${WHEEL_M}" r="${WHEEL_R}" l="${WHEEL_L}" />
            </link>
            <gazebo reference="${prefix}_wheel">
                <material>Gazebo/Black</material>
            </gazebo>
        </xacro:macro>
    
        <!-- Start Modelling -->
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${BASE_X} ${BASE_Y} ${BASE_Z}"/>
                </geometry>
                <material name="purple"/>
            </visual>
    
            <collision>
                <geometry>
                    <box size="${BASE_X} ${BASE_Y} ${BASE_Z}"/>
                </geometry>
            </collision>
    
            <xacro:BoxInertial m="${BASE_M}" x="${BASE_X}" y="${BASE_Y}" z="${BASE_Z}" />
        </link>
        <gazebo reference="base_link">
            <material>Gazebo/Purple</material>
        </gazebo>

        <joint name="footprint_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 -${BASE_Z/2 + CASTER_R}"/>
        </joint>

        <link name="base_footprint" />
    
        <joint name="caster_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_ball"/>
            <origin xyz="${CASTER_OFF_X} 0 ${CASTER_OFF_Z}"/>
        </joint>
    
        <link name="caster_ball">
            <visual>
                <geometry>
                    <sphere radius="${CASTER_R}"/>
                </geometry>
                <material name="gray"/>
            </visual>
    
            <collision>
                <geometry>
                    <sphere radius="${CASTER_R}"/>
                </geometry>
            </collision>
    
            <xacro:SphereInertial m="${CASTER_M}" r="${CASTER_R}" />
        </link>
    
        <gazebo reference="caster_ball">
            <material>Gazebo/Gray</material>
            <mu1>0.0001</mu1>
            <mu2>0.0001</mu2>
        </gazebo>
    
        <xacro:Wheel prefix="left" y_reflect="1" />
        <xacro:Wheel prefix="right" y_reflect="-1" />
        
</robot>